---
title: "Hospitality"
output:
  pdf_document: default
  #html_document: default
date: "2023-07-03"
---


## R Markdown

This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things.



```{r }
#Reading the dataset
#libraries
library(dplyr)
library(ggplot2)
library(caret)
library(tidyverse)
#install.packages("xgboost")
library(xgboost)
library(doParallel)
hos_data <- read.csv("csv/output.csv", header=T)
head(hos_data)
```



```{r }
#Summarizing the dataset
summary(hos_data)
```


```{r }
ggplot(hos_data, aes(is_canceled, fill = factor(is_canceled))) +
  geom_bar()+
  labs(title = "Cancellation")+ theme_light()
```


```{r }

#Bar plot of Market Segmant and Hotel Type
ggplot(hos_data, aes(market_segment, fill = hotel)) +
  geom_bar(position = position_dodge()) +
  labs(title = "Booking Status Market Segment",
       x = "Market Segment",
       y = "Count")+ theme_light()+
  theme(axis.text.x = element_text(angle = 30))
```





```{r  echo=TRUE}
#Visualization 
hos_data$arrival_date_month <-
  factor(hos_data$arrival_date_month, levels = month.name)


ggplot(data = hos_data, aes(x = arrival_date_month)) +
  geom_bar(fill =  "#00BFC4") +
  geom_text(stat = "count", aes(label = ..count..), hjust = 1) +
  coord_flip() + labs(title = "Arrival Date by Month",
                      x = "Month",
                      y = "Count") +
  theme_minimal()
```



```{r  echo=TRUE}
#create dummy variables expect for the response
dummies_model <- dummyVars(is_canceled~ ., data = hos_data)
#if the response is a factor may get a warning that you can ignore


#provide only predictors that are now converted to dummy variables
hos_predictors_dummy<- data.frame(predict(dummies_model, newdata = hos_data)) 

#recombine predictors including dummy variables with response
hos_data <- cbind(is_canceled=hos_data$is_canceled, hos_predictors_dummy) 

#change reponse to a factor
hos_data$is_canceled<-as.factor(hos_data$is_canceled)


# rename resonse 
hos_data$is_canceled<-fct_recode(hos_data$is_canceled, is_canceled = "1",notCanceled = "0")

# relevel response
hos_data$is_canceled<- relevel(hos_data$is_canceled, ref = "is_canceled")

#make sure levels are correct
levels(hos_data$is_canceled)
```


```{r }
#Partition the data into test and train data
set.seed(99)
index <-createDataPartition(hos_data$is_canceled, p = .8,list = FALSE)
hos_train <- hos_data[index,]

hos_test <- hos_data[-index,]

```

```{r }
#Running the xgboost model


#total number of cores on your computer
num_cores<-detectCores(logical=FALSE)

#Snce the model takes a lot of time to run, parallel processing can speed up the process
cl <- makePSOCKcluster(num_cores-1)
registerDoParallel(cl)


set.seed(8)
model_gbm <- train(is_canceled ~ .,
                   data = hos_train,
                   method = "xgbTree",
                   trControl =trainControl(method = "cv", 
                                           number = 5,
                                           classProbs = TRUE,
                                           summaryFunction = twoClassSummary),
                   # provide a grid of parameters
                   tuneGrid = expand.grid(
                     nrounds = c(50,200),
                     eta = c(0.025, 0.05),
                     max_depth = c(2, 3),
                     gamma = 0,
                     colsample_bytree = 1,
                     min_child_weight = 1,
                     subsample = 1),
                     na.action=na.exclude,
                     metric="ROC"
                   )

#stop parallel processing
stopCluster(cl)

registerDoSEQ()
 model_gbm
```


```{r }
#plotting the model
plot(model_gbm)
```


```{r }
#plotting the model
plot(varImp(model_gbm, scale=FALSE), top = 15)
```


```{r }
#plotting the shap model
library(SHAPforxgboost)
data<- subset(hos_train, select = -c(is_canceled))
Xdata <- as.matrix(data)
shap <- shap.prep(model_gbm$finalModel, X_train = Xdata, top_n = 15)

# SHAP importance plot
shap.plot.summary(shap)
```



```{r }
shap.plot.dependence(shap, x = "total_of_special_requests",
                     color_feature = "total_of_special_requests")
```


```{r }
shap.plot.dependence(shap, x = "lead_time",
                     color_feature = "lead_time")
```


```{r }
# Use 4 most important predictor variables
top4<-shap.importance(shap, names_only = TRUE)[1:4]

for (x in top4) {
  p <- shap.plot.dependence(
    shap, 
    x = x, 
    color_feature = "auto", 
    smooth = FALSE, 
    jitter_width = 0.01, 
    alpha = 0.4
  ) +
    ggtitle(x)
  print(p)
}
```



```{r }
library(ROCR)
hos_prob<- predict(model_gbm, hos_test, type="prob")
pred = prediction(hos_prob[,2], hos_test$is_canceled,label.ordering =c("is_canceled","notCanceled")) 
perf = performance(pred, "tpr", "fpr")

plot(perf, colorize=TRUE)

```

```{r }
#Printing the AUC
slot(performance(pred, "auc"), "y.values")[[1]]
```
